# Generated by Django 3.2.9 on 2021-12-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('created_at', models.BigIntegerField()),
                ('updated_at', models.BigIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('combines', models.CharField(max_length=100)),
                ('totalable', models.BooleanField()),
                ('render', models.BooleanField()),
                ('customer', models.CharField(max_length=100)),
            ],
        ),
    ]
