# Generated by Django 3.2.9 on 2021-12-16 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_segments_inventory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inventory',
            new_name='Segments',
        ),
    ]
