# Generated by Django 3.2.9 on 2021-12-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_inventory_segments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segments',
            name='combines',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
