# Generated by Django 3.2.9 on 2021-12-23 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('api', '0005_alter_segments_combines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segments',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customers'),
        ),
    ]
