# Generated by Django 3.2.9 on 2021-12-23 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('created_at', models.BigIntegerField()),
                ('updated_at', models.BigIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(blank=True, max_length=100)),
                ('world_viewable', models.BooleanField()),
            ],
        ),
    ]
